services:
  database:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_DATABASE: mcs
      MYSQL_ROOT_PASSWORD: 123456
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./script.sql:/docker-entrypoint-initdb.d/script.sql # Initialize the database with the provided SQL file
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - mcs-network
  redis:
    image: redis:latest
    container_name: mcs-redis
    ports:
      - 6379:6379
    networks:
      - mcs-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: mcs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mcs-network
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: mcs-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: mcs-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      mcs-network:
volumes:
  mysql_data:
networks:
  mcs-network:
    driver: bridge
