# config not used eureka server
#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/user/**
#
#        - id: order-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/order/**

server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**

        - id: user-service-auth
          uri: lb://user-service
          predicates:
              - Path=/api/v1/auth/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

