server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/mcs1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
